package jetbrains.mps.json.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int JsonArray = 0;
  public static final int JsonDocument = 1;
  public static final int JsonElement = 2;
  public static final int JsonFile = 3;
  public static final int JsonSet = 4;
  public static final int JsonValue = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xec603e7355e84c6bL, 0xac1ff7a01e487844L);
    builder.put(0x7a7726483cf8d791L, JsonArray);
    builder.put(0x7a7726483cf8d777L, JsonDocument);
    builder.put(0x7a7726483cf8d778L, JsonElement);
    builder.put(0x7a7726483cf8d776L, JsonFile);
    builder.put(0x7a7726483cf8d786L, JsonSet);
    builder.put(0x7a7726483cf8d782L, JsonValue);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
