package jetbrains.mps.json.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptJsonArray = createDescriptorForJsonArray();
  /*package*/ final ConceptDescriptor myConceptJsonDocument = createDescriptorForJsonDocument();
  /*package*/ final ConceptDescriptor myConceptJsonElement = createDescriptorForJsonElement();
  /*package*/ final ConceptDescriptor myConceptJsonFile = createDescriptorForJsonFile();
  /*package*/ final ConceptDescriptor myConceptJsonSet = createDescriptorForJsonSet();
  /*package*/ final ConceptDescriptor myConceptJsonValue = createDescriptorForJsonValue();
  private final LanguageConceptSwitch myConceptIndex;

  public StructureAspectDescriptor() {
    myConceptIndex = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptJsonArray, myConceptJsonDocument, myConceptJsonElement, myConceptJsonFile, myConceptJsonSet, myConceptJsonValue);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myConceptIndex.index(id)) {
      case LanguageConceptSwitch.JsonArray:
        return myConceptJsonArray;
      case LanguageConceptSwitch.JsonDocument:
        return myConceptJsonDocument;
      case LanguageConceptSwitch.JsonElement:
        return myConceptJsonElement;
      case LanguageConceptSwitch.JsonFile:
        return myConceptJsonFile;
      case LanguageConceptSwitch.JsonSet:
        return myConceptJsonSet;
      case LanguageConceptSwitch.JsonValue:
        return myConceptJsonValue;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myConceptIndex.index(c);
  }

  private static ConceptDescriptor createDescriptorForJsonArray() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.mps.json", "JsonArray", 0xec603e7355e84c6bL, 0xac1ff7a01e487844L, 0x7a7726483cf8d791L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.json.structure.JsonElement", 0xec603e7355e84c6bL, 0xac1ff7a01e487844L, 0x7a7726483cf8d778L);
    b.origin("r:3888aa22-4be6-408f-b060-b135b1a065c3(jetbrains.mps.json.structure)/8824564086558218129");
    b.aggregate("values", 0x7a7726483cf8d792L).target(0xec603e7355e84c6bL, 0xac1ff7a01e487844L, 0x7a7726483cf8d782L).optional(false).ordered(true).multiple(true).origin("8824564086558218130").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForJsonDocument() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.mps.json", "JsonDocument", 0xec603e7355e84c6bL, 0xac1ff7a01e487844L, 0x7a7726483cf8d777L);
    b.class_(false, false, false);
    b.origin("r:3888aa22-4be6-408f-b060-b135b1a065c3(jetbrains.mps.json.structure)/8824564086558218103");
    b.aggregate("elements", 0x7a7726483cf8d779L).target(0xec603e7355e84c6bL, 0xac1ff7a01e487844L, 0x7a7726483cf8d778L).optional(true).ordered(true).multiple(true).origin("8824564086558218105").done();
    b.alias("json document");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForJsonElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.mps.json", "JsonElement", 0xec603e7355e84c6bL, 0xac1ff7a01e487844L, 0x7a7726483cf8d778L);
    b.class_(false, true, false);
    b.origin("r:3888aa22-4be6-408f-b060-b135b1a065c3(jetbrains.mps.json.structure)/8824564086558218104");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForJsonFile() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.mps.json", "JsonFile", 0xec603e7355e84c6bL, 0xac1ff7a01e487844L, 0x7a7726483cf8d776L);
    b.class_(false, false, true);
    b.origin("r:3888aa22-4be6-408f-b060-b135b1a065c3(jetbrains.mps.json.structure)/8824564086558218102");
    b.aggregate("document", 0x7a7726483cf8d77cL).target(0xec603e7355e84c6bL, 0xac1ff7a01e487844L, 0x7a7726483cf8d777L).optional(false).ordered(true).multiple(false).origin("8824564086558218108").done();
    b.alias("json file");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForJsonSet() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.mps.json", "JsonSet", 0xec603e7355e84c6bL, 0xac1ff7a01e487844L, 0x7a7726483cf8d786L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.json.structure.JsonElement", 0xec603e7355e84c6bL, 0xac1ff7a01e487844L, 0x7a7726483cf8d778L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:3888aa22-4be6-408f-b060-b135b1a065c3(jetbrains.mps.json.structure)/8824564086558218118");
    b.aggregate("elements", 0x7a7726483cf8d787L).target(0xec603e7355e84c6bL, 0xac1ff7a01e487844L, 0x7a7726483cf8d778L).optional(false).ordered(true).multiple(true).origin("8824564086558218119").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForJsonValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.mps.json", "JsonValue", 0xec603e7355e84c6bL, 0xac1ff7a01e487844L, 0x7a7726483cf8d782L);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.json.structure.JsonElement", 0xec603e7355e84c6bL, 0xac1ff7a01e487844L, 0x7a7726483cf8d778L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:3888aa22-4be6-408f-b060-b135b1a065c3(jetbrains.mps.json.structure)/8824564086558218114");
    b.prop("value", 0x7a7726483cf8d783L, "8824564086558218115");
    return b.create();
  }
}
